kind: pipeline
type: docker
name: default

steps:
steps:
  - name: install
    image: node:16 # 选择合适的 Node.js 版本
    commands:
      - npm config set registry https://registry.npmmirror.com
      - npm config set fetch-retries 5 # 设置重试次数
      - npm config set fetch-timeout 60000 # 设置超时时间为 60 秒
      - npm install

  - name: build
    image: node:16
    commands:
      - npm run build # 运行 umi 的构建脚本

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 121.40.217.207
      username: root
      password:
        from_secret: ECS_PSD
      script:
        - echo "Copying build files to Nginx directory..."
        - cp -r ./dist/* /usr/share/nginx/html